In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import ast

In [4]:
ast.literal_eval

<function ast.literal_eval(node_or_string)>

In [5]:
result = pd.read_csv("../Downloads/result.txt")

In [6]:
result.iloc[:,0].apply(lambda x : ast.literal_eval(x))

0     [[2.0, 0.9960644841194153, 0.5452047281605839,...
1     [[2.0, 0.9842441082000732, 0.5288163614930705,...
2     [[2.0, 0.9811444878578186, 0.5282314472233582,...
3     [[1.0, 0.9719263911247253, 0.25978022371833087...
4     [[3.0, 0.9486952424049377, 0.22164477782147923...
                            ...                        
90    [[2.0, 0.995159924030304, 0.6350265586538449, ...
91    [[2.0, 0.995159924030304, 0.6350265260714156, ...
92    [[2.0, 0.9923132061958313, 0.598976152112628, ...
93    [[2.0, 0.9823686480522156, 0.6187851734657714,...
94    [[2.0, 0.9885335564613342, 0.6086541213967903,...
Name: (C) 2017-2020, Length: 95, dtype: object

In [7]:
path = pd.read_csv('../Downloads/query (1).csv')

In [8]:
path['label'] = result.iloc[:,0]

In [9]:
path['label'] = result.iloc[:,0].apply(lambda x : np.asarray(pd.DataFrame(np.array(ast.literal_eval(x))).groupby(0).nth(0).reset_index()).tolist())

In [10]:
path.to_csv('drawing_box_img_label.csv',index=None)

In [12]:
np.where(path['label'][0][:,1] > 0.5)

TypeError: list indices must be integers or slices, not tuple

In [14]:
np.asarray(pd.DataFrame(path['label'][0]).groupby(0).nth(0).reset_index())

array([[1.        , 0.15939173, 0.47020509, 0.31245921, 0.77327819,
        0.58162958],
       [2.        , 0.99606448, 0.54520473, 0.03336033, 0.77494247,
        0.94836464],
       [3.        , 0.05935808, 0.3646031 , 0.06666991, 0.7970975 ,
        0.33806911],
       [4.        , 0.08074357, 0.35938019, 0.05855391, 0.71555285,
        0.27684906],
       [5.        , 0.8685742 , 0.47646574, 0.17659644, 0.62669494,
        0.32048056],
       [6.        , 0.48467171, 0.40499562, 0.31987672, 0.46865551,
        0.50092862]])

In [22]:
path['label'] = result.iloc[:,0].apply(lambda x : np.asarray(pd.DataFrame(np.array(ast.literal_eval(x))).groupby(0).nth(0).reset_index()))

In [23]:
hdoorassy = path.iloc[[3,15,16,17,18,19,20,21,23,29,30,31,32,33,34,35,36,37,39,40,43,44,45,47,48,49,53,55,56,57,58,59,60,61,64,66,67,68,69,70,71,72,73,74,75,76,77,78,80,81,82,83,84,85,87,88,89],:]

In [75]:
hdoorassy['label'][3][:,0] == 5

array([False, False,  True, False])

### fancy indexing 

In [92]:
guidshoe = path.iloc[[4,6,7,8,9,10,13,22,24,25,26,27,38,52,63]]

In [91]:
hdoorassy['label'].apply(lambda x : x[x[:,0]==1][:,1]).mean()

array([0.96761493])

In [97]:
guidshoe['label'].apply(lambda x : x[x[:,0]==3][:,1]).mean()

array([0.55442836])

In [99]:
path.to_csv('backlog_result.csv',index=False)

In [111]:
path['label']=path['label'].apply(lambda x : np.around(x[:,:2],2))

In [113]:
path.to_csv('backlog_score.csv',index=False)